# Generated by Django 2.2.12 on 2021-08-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado_area', models.TextField(blank=True, null=True)),
                ('estado_area', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Area',
                'managed': False,
            },
        ),
    ]
