# Generated by Django 2.2.12 on 2021-08-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_pregunta',
            fields=[
                ('id_tipo_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tipo_pregunta',
                'managed': False,
            },
        ),
    ]
