# Generated by Django 2.2.12 on 2021-08-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tipo_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado_pregunta', models.TextField(blank=True, null=True)),
                ('estado_pregunta', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pregunta',
                'managed': False,
            },
        ),
    ]
