# Generated by Django 2.2.12 on 2021-08-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Respuesta',
                'managed': False,
            },
        ),
    ]
