# Generated by Django 2.2.12 on 2021-08-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta_contestada',
            fields=[
                ('id_encuesta_contestada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Encuesta_contestada',
                'managed': False,
            },
        ),
    ]
