# Generated by Django 2.2.12 on 2021-08-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_encuesta_contestada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_opcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Opcion',
                'managed': False,
            },
        ),
    ]
