# Generated by Django 2.2.12 on 2021-08-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_opcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion_persona', models.TextField(blank=True, null=True)),
                ('codigo_persona', models.TextField(blank=True, null=True)),
                ('nombre_persona', models.TextField(blank=True, null=True)),
                ('apellido_persona', models.TextField(blank=True, null=True)),
                ('correo_persona', models.TextField(blank=True, null=True)),
                ('telefono_persona', models.TextField(blank=True, null=True)),
                ('direccion_persona', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Persona',
                'managed': False,
            },
        ),
    ]
