# Generated by Django 2.2.12 on 2021-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Rol',
                'managed': False,
            },
        ),
    ]
